FROM fedora:25
LABEL maintainer "Trevor SANDY <trevor.sandy@gmail.com>"
RUN dnf install -y git wget unzip finger which rpmlint ccache dnf-plugins-core rpm-build
RUN dnf install -y qt5-qtbase-devel qt5-qttools-devel
RUN dnf install -y OpenEXR-devel boost-devel SDL2-devel mesa-libOSMesa-devel mesa-libGLU-devel freeglut-devel tinyxml-devel gl2ps-devel libtiff-devel
RUN dnf update -x kernel* -y
RUN dnf install -y sudo \
    && groupadd -r user -g 1000 \
    && useradd -u 1000 -r -g user -m -d /user -s /sbin/nologin -c "Build pkg user" user \
    && chmod 755 /user \
    && echo "user ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/user \
    && chmod 0440 /etc/sudoers.d/user
WORKDIR /user
USER user
VOLUME /buildpkg
CMD wget https://raw.githubusercontent.com/trevorsandy/lpub3d-ci/master/builds/linux/CreateRpm.sh \
    && export DOCKER=true \
    && chmod +x CreateRpm.sh \
    && ./CreateRpm.sh \
    && if test -d /buildpkg; then \
      sudo cp -f /user/rpmbuild/RPMS/`uname -m`/*.rpm /buildpkg/; \
      sudo cp -f /user/*.log /buildpkg/; \
    fi
