FROM ubuntu:xenial
ARG DEBIAN_FRONTEND=noninteractive
LABEL maintainer "Trevor SANDY <trevor.sandy@gmail.com>"
RUN apt-get update ; apt-get install -y apt-utils git wget unzip lintian build-essential debhelper fakeroot ccache lsb-release
RUN apt-get install -y qtbase5-dev qt5-qmake qt5-default libqt5opengl5-dev libpng-dev libjpeg-dev zlib1g-dev
RUN apt-get install -y libsndio-dev libopenexr-dev libilmbase-dev libboost-dev libboost-date-time-dev libboost-thread-dev libsdl2-dev libtiff5-dev libosmesa6-dev freeglut3-dev libtinyxml-dev libgl2ps-dev
RUN apt-get install -y libx11-dev autotools-dev autoconf pkg-config libtool curl
RUN apt-get install -y sudo \
    && groupadd -r user -g 1000 \
    && useradd -u 1000 -r -g user -m -d /user -s /sbin/nologin -c "Build pkg user" user \
    && chmod 755 /user \
    && echo "user ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/user \
    && chmod 0440 /etc/sudoers.d/user
WORKDIR /user
USER user
VOLUME /buildpkg
CMD wget https://raw.githubusercontent.com/trevorsandy/lpub3d-ci/master/builds/linux/CreateDeb.sh \
    && chmod +x CreateDeb.sh \
    && ./CreateDeb.sh \
    && if test -d /buildpkg; then \
      sudo cp -f /user/debbuild/*.deb /buildpkg/; \
      sudo cp -f /user/debbuild/*.dsc /buildpkg/; \
      sudo cp -f /user/debbuild/*.changes /buildpkg/; \
      sudo cp -f /user/*.log /buildpkg/; \
    fi
