#!/bin/sh
#  Trevor SANDY <trevor.sandy@gmail.com>
#  Last Update: May 31, 2025
#  Copyright (C) 2017 - 2025 by Trevor SANDY

prefix="$( cd "$( dirname "$0" )" && pwd )"
includedir=${prefix}/include
libdir=${prefix}/lib
prefix_set=no

usage="\
Usage: $0 [--prefix[=DIR]] [--version] [--libdir] [--cflags] [--ldflags ] [--ldlibs] [--libs] [--static-libs] [--static-libs-explicit]"

if test $# -eq 0; then
  echo "${usage}" 1>&2
  exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=$(echo "$1" | sed 's/[-_a-zA-Z0-9]*=//') ;;
  *) optarg= ;;
  esac

  case $1 in
    --version)
      echo 21.3.9
      ;;
    --prefix)
      echo ${prefix}
      ;;
    --prefix=*)
      prefix=$optarg
      if test $prefix_set = no ; then
        prefix=$optarg
        includedir=${prefix}/include
        libdir=${prefix}/lib
        prefix_set=yes
      fi
      ;;
    --libdir)
      echo -L${libdir}
      ;;
    --cflags)
      echo ${includedir}
      ;;
    --ldflags)
      echo -lpthread -lm -ldl
      ;;
    --ldlibs)
      echo -l@mesa@ -lGLU
      ;;
    --libs)
      echo -L${libdir} -l@mesa@ -lGLU
      ;;
    --libs-explicit)
      echo ${libdir}/lib@mesa@.a ${libdir}/libGLU.a
      ;;
    --static-libs)
      echo -L${libdir} -l@mesa@ -GLU -lpthread -lm -ldl
      ;;
    --static-libs-explicit)
      echo ${libdir}/lib@mesa@.a ${libdir}/libGLU.a -lpthread -lm -ldl
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
