# Build and check LPub3D on Linux and macOS
# Trevor SANDY <trevor.sandy@gmail.com>
# Last Update: May 10, 2025
# Copyright (C) 2017 - 2025 by Trevor SANDY
#
os: linux

dist: xenial

language: cpp

git:
  depth: false

cache:
  ccache: true
  directories:
  - "${LP3D_LDRAW_DIR}"
  - "${LP3D_DIST_DIR_BASE}"

# The following variables can be set to true from
# Travis-CI Site->More Options->Settings->Environment Variables
# LP3D_SKIP_TRAVIS_VAR     ; skip Travis-CI build
# LP3D_BUILD_PKG_VAR       ; trigger package build
# LP3D_TEST_SF_DEPLOY_VAR  ; test deploy SourceForge
# LP3D_SKIP_SF_DEPLOY_VAR  ; skip SourceForge deploy
# LP3D_BUILD_RENDERERS_VAR ; build specified renderer(s) in compile only configuration
# LP3D_BUILD_LDGLITE_VAR   ; rebuild LDGLite
# LP3D_BUILD_LDVIEW_VAR    ; rebuild LDView
# LP3D_BUILD_POVRAY_VAR    ; rebuild LPub3D-Trace (POV-Ray)
# LP3D_BUILD_MESALIB_VAR   ; rebuild Mesa library
# LP3D_UPLOADTOOL_REV_VAR  ; set upload.sh revision - default is master (latest)
# LP3D_AI_MAGIC_BYTES_VAR  ; do not patch out ARM AppImage magic bytes
#
# Remove LP3D_BUILD_PKG_VAR to enable LP3D_COMPILE_SOURCE (compile source only)
#
env:
  global:
  - LP3D_QT_BASE=515
  - LP3D_LDRAW_DIR=${HOME}/ldraw
  - LP3D_BUILD_FOLDER=${TRAVIS_BUILD_DIR}
  - LP3D_RELEASES_DIR=${LP3D_BUILD_FOLDER}/builds/releases
  - LP3D_LOGS_DIR=${LP3D_RELEASES_DIR}/logs
  - LP3D_UPDATE_ASSETS=${LP3D_RELEASES_DIR}/updates
  - LP3D_DOWNLOAD_ASSETS=${LP3D_RELEASES_DIR}/downloads
  - LP3D_3RD_BUILD_FOLDER=${LP3D_BUILD_FOLDER}/..
  - LP3D_DIST_DIR_BASE=${LP3D_3RD_BUILD_FOLDER}/lpub3d_3rdparty_base
  - LP3D_COMPOSE_DIR=builds/linux/docker-compose
  - LP3D_CI_DIR=builds/utilities/ci
  - LP3D_SECURE_DIR=builds/utilities/ci/secure
  - LP3D_CI_SCRIPT_DIR=builds/utilities/ci/travis
  - LP3D_DROPBOX_BUILDS_DIR=travis-ci/builds
  - LP3D_DROPBOX_RELEASES_DIR=travis-ci/releases
  - LP3D_DROPBOX_LOGS_DIR=${LP3D_DROPBOX_RELEASES_DIR}/logs
  - LP3D_DROPBOX_UPDATES_DIR=${LP3D_DROPBOX_RELEASES_DIR}/updates
  - LP3D_DROPBOX_DOWNLOADS_DIR=${LP3D_DROPBOX_RELEASES_DIR}/downloads
  - LP3D_RELEASE_LABEL="LPub3D $(date +'%d.%m.%Y')"
  - LP3D_VER_LDGLITE=ldglite-1.3
  - LP3D_VER_LDVIEW=ldview-4.6
  - LP3D_VER_POVRAY=lpub3d_trace_cui-3.8
  - LP3D_VER_MESALIB=mesa
  - LP3D_RELEASE_DESCRIPTION="LPub3D - An LDraw™ editor for LEGO® style digital building
    instructions."
  - LP3D_UPLOADTOOL_REV=master
  - LP3D_DOCKER_COMPOSE_VERSION=1.28.5
  
addons:
  ssh_known_hosts: trevorsandy@frs.sourceforge.net

stages:
- name: Prepare Build Storage
  if: tag IS blank AND env(LP3D_BUILD_PKG_VAR) = true
- name: Prepare Release Storage
  if: tag =~ ^(?!$)(?:v[0-9]+\.[0-9]+\.[0-9]+_?[^\W]*)?$
- name: Build, Check and Package
  if: env(LP3D_BUILD_PKG_VAR) = true
- name: Compile Source
  if: tag IS blank AND NOT env(LP3D_BUILD_PKG_VAR) = true
- name: GitHub and Sourceforge Deploy
  if: tag =~ ^(?!$)(?:v[0-9]+\.[0-9]+\.[0-9]+_?[^\W]*)?$

before_install:
- source ${LP3D_CI_SCRIPT_DIR}/before_install
install:
- source ${LP3D_CI_SCRIPT_DIR}/install
before_script:
- source ${LP3D_CI_SCRIPT_DIR}/before_script
script:
- source ${LP3D_CI_SCRIPT_DIR}/script
after_script:
- source ${LP3D_CI_SCRIPT_DIR}/after_script

jobs:
  fast_finish: true
  include:
  - stage: Prepare Build Storage
    name: Build Storage
    env: LP3D_BUILD_STORAGE=true
    os: linux
    compiler: gcc
    script: source ${LP3D_CI_SCRIPT_DIR}/prepare_store
  - stage: Prepare Release Storage
    name: Release Storage
    env: LP3D_DEPLOY_PACKAGES=true
    os: linux
    compiler: gcc
    script: source ${LP3D_CI_SCRIPT_DIR}/prepare_store
  - stage: Build, Check and Package
    name: macOS
    env: LP3D_BUILD_OS=macos
    os: osx
    osx_image: xcode11.3
    compiler: clang
    addons:
      homebrew:
        packages:
          - grep
          - qt5
  - stage: Build, Check and Package
    name: Arch Linux
    env: LP3D_BUILD_OS=archlinux
    os: linux
    compiler: gcc
  - stage: Build, Check and Package
    name: Fedora 36
    env: LP3D_BUILD_OS=fedora
    os: linux
    compiler: gcc
  - stage: Build, Check and Package
    name: Ubuntu Jammy
    env: LP3D_BUILD_OS=ubuntu
    os: linux
    compiler: gcc
  - stage: Build, Check and Package
    name: AppImage AMD64
    env: LP3D_BUILD_OS=appimage
    os: linux
    arch: amd64
    dist: xenial
    compiler: gcc
  - stage: Build, Check and Package
    name: AppImage ARM64
    env: LP3D_BUILD_OS=appimage
    os: linux
    arch: arm64
    dist: xenial
    compiler: gcc
    addons:
      apt:
        packages:
          - autoconf
          - automake
          - autotools-dev
          - build-essential
          - cmake
          - debhelper
          - freeglut3-dev
          - libboost-date-time-dev
          - libboost-dev
          - libboost-thread-dev
          - libgl1-mesa-dev
          - libgl2ps-dev
          - libjpeg-dev
          - libopenexr-dev
          - libosmesa6-dev
          - libpng-dev
          - libqt5opengl5-dev
          - libsdl2-dev
          - libsndio-dev
          - libtiff5-dev
          - libtinyxml-dev
          - libtool
          - libx11-dev
          - libxss-dev
          - pkg-config
          - qt5-default
          - qt5-qmake
          - qtbase5-dev
          - qttools5-dev-tools
          - unzip
          - x11proto-dri2-dev
          - x11proto-gl-dev
          - xvfb
          - zip
          - zlib1g-dev
  - stage: Compile Source
    name: Ubuntu
    env: LP3D_COMPILE_SOURCE=true
    os: linux
    compiler: gcc
  - stage: Compile Source
    name: macOS
    env: LP3D_COMPILE_SOURCE=true
    os: osx
    osx_image: xcode11.3
    compiler: clang
    addons:
      homebrew:
        packages:
          - grep
          - qt5
  - stage: GitHub and Sourceforge Deploy
    name: Deploy LPub3D
    env: LP3D_DEPLOY_PACKAGES=true
    script: source ${LP3D_CI_SCRIPT_DIR}/releases
    deploy:
      provider: releases
      name: "$LP3D_RELEASE_LABEL"
      release_notes: "$LP3D_RELEASE_DESCRIPTION"
      token:
        secure: GRl0LOJ8M5ow1qik8t2+tJsqMDo53v/TRfxprWg5C+3DR3ny/CgR5mODMtpR4LgSyMeD5yhGovxHAbzgUyutne9PT0BagI8zdt/ZMqcLnvPQyzJlhfy3t2TVcJRoVXcoUUF0ZJHrpr9WD8C7xnjMp7w/j+HThQuX+8CD3gCwZhYkDRuNgtJY/PT+nwITjC4WJuF0xxYOyLJROebQZ1LJ24HY0zVtg+JJZPslkQHgoBg/ozO8JNXgYaYe3VgcyQSnUMqE/SjMBGYMR9RlNwYXCJLeYHiY3fej33z7UPZOH/kPQ8RhKpJi9qqOTtYj38dTxmpiJjOJ4SyeKXvsyymc5ekwSdlJe6rVWKKAXFMegH/4i3Nk8HKmfxMPLklprusFEMQo2CdA5UeNRuWJ/HfDpywbQwFLC6ThNZcS6wqOqf2Rzy6QRNFWlH9eJoiSMyQRVTFGwQ3bf2MXXJSloFuxRpGYoejWt36O+rNZnTR6+Xz1r2KyaaFizCGen082klzmfdoCl0mh+m9Jix7ypzgNBKISFI5DTbjr6Qt+D5dVdp5PWGBAbhTd6JtcG64P9fDUWq5X9ypFj6Jb1626sHFlYQKCSX+lEpjbd4UTSbTxO35NMTO1g90xKMJeIpvsCwm9DcWl+jGmt9cwSHxTQuWkeEaUcoywYvA4kTjIpDuIaR8=
      file_glob: true
      file: "$LP3D_DOWNLOAD_ASSETS/*"
      overwrite: true
      edge: true # opt in to dpl v2
      on:
        repo: trevorsandy/lpub3d
        branch: "$TRAVIS_BRANCH"
        condition: "$LP3D_DEPLOY_PKG = yes"

branches:
  except:
    - # Do not build tags that we create for upload to GitHub Releases
    - /^(?i:continuous)/

notifications:
  email:
    on_success: never
    on_failure: always
