#!/bin/bash
#
# Travis build [before_install] procedures
#
#  Trevor SANDY <trevor.sandy@gmail.com>
#  Last Update: December 26, 2017
#  Copyright (c) 2017 by Trevor SANDY
#

# Skip build if the commit message contains [skip travis] or [travis skip]
echo "$TRAVIS_COMMIT_MESSAGE" | grep -E '\[(skip travis|travis skip)\]' \
&& echo "[skip travis] detected, exiting." \
&& exit 0 || true

# Build package if commit message contains [build pkg]
echo "$TRAVIS_COMMIT_MESSAGE" | grep -E '\[build pkg.*\]' \
&& export LP3D_BUILD_PKG=yes \
&& echo "[build pkg] detected." || true

# Build and deploy package if pushed tag exists and has a valid format (vN.N.N[-A])
echo "$TRAVIS_TAG" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+\S*' \
&& echo "Deploy tag $TRAVIS_TAG detected." \
&& export LP3D_BUILD_PKG=yes \
&& export LP3D_DEPLOY_PKG=yes || true

# Add private qt repositories
if [[ "$TRAVIS_OS_NAME" = "linux" && "$LP3D_COMPILE_SOURCE" = "true" && "$LP3D_BUILD_PKG" = "" && "$LP3D_DEPLOY_PACKAGES" = "" ]]; then
  if [ "$LP3D_QT_BASE" = "52" ]; then sudo add-apt-repository ppa:beineri/opt-qt521-trusty -y; fi;
  if [ "$LP3D_QT_BASE" = "53" ]; then sudo add-apt-repository ppa:beineri/opt-qt532-trusty -y; fi;
  if [ "$LP3D_QT_BASE" = "54" ]; then sudo add-apt-repository ppa:beineri/opt-qt542-trusty -y; fi;
  if [ "$LP3D_QT_BASE" = "55" ]; then sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y; fi;
  if [ "$LP3D_QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y; fi;
  if [ "$LP3D_QT_BASE" = "57" ]; then sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y; fi;
  if [ "$LP3D_QT_BASE" = "58" ]; then sudo add-apt-repository ppa:beineri/opt-qt58-trusty  -y; fi;
  if [ "$LP3D_QT_BASE" = "59" ]; then sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y; fi;
fi
# Parse the commit message for 3rd party build override. As 3rd party items are not expected to change often
# we cache them to speed up the build. If/when it is necessary to build one of the items, we signa with 1 in the commit message.
# The format is [build pkg 1 1 1] to build all 3rd party itmes. The first position is LDGlite, the second is LDView and the
# third is LPub3D_Trace (POV-Ray). Alternatively you may choose to build only one of the items in which case the settings would
# be ...1 0 0 to only build LDGlite. It is also possible to override the cache when just compiling the source by entering
# 'build 3rdpkg 1 1 1' in the commit message.
if [ "$LP3D_BUILD_PKG" = "yes" ]; then
  LP3D_BUILD_3RD=$(echo "$TRAVIS_COMMIT_MESSAGE" | sed -n -e 's/^.*build pkg //p' -e 's/^.*deploy pkg //p' | sed 's/].*//g');
elif [ "$LP3D_COMPILE_SOURCE" = "true" ]; then
  LP3D_BUILD_3RD=$(echo "$TRAVIS_COMMIT_MESSAGE" | sed -n -e 's/^.*build 3rdpkg //p');
fi;
export LP3D_BUILD_LDGLITE=$(echo "$LP3D_BUILD_3RD" | cut -d' ' -f 1);
export LP3D_BUILD_LDVIEW=$(echo "$LP3D_BUILD_3RD" | cut -d' ' -f 2);
export LP3D_BUILD_POVRAY=$(echo "$LP3D_BUILD_3RD" | cut -d' ' -f 3);
# Update repository index and download package build dependencies if required
if [ "$TRAVIS_OS_NAME" = "linux" ]; then
  if [[ "$LP3D_COMPILE_SOURCE" = "true" && "$LP3D_BUILD_PKG" = "" && "$LP3D_DEPLOY_PACKAGES" = "" ]]; then
    sudo apt-get update -qq;
  fi;
  export LP3D_DIST_DIR=lpub3d_linux_3rdparty;
else
  if [[ "$LP3D_COMPILE_SOURCE" = "true" && "$LP3D_BUILD_PKG" = "" ]]; then
    brew install ccache;
    LP3D_EXP_CCACHE_PATH=true;
  fi;
  if [[ "$LP3D_BUILD_MACOS" = "true" && "$LP3D_BUILD_PKG" = "yes" ]]; then
    brew install ccache openexr sdl2 tinyxml gl2ps libtiff libjpeg minizip;
    LP3D_EXP_CCACHE_PATH=true;
  fi;
  if [ "$LP3D_EXP_CCACHE_PATH" = "true" ]; then
    export PATH="/usr/local/opt/ccache/libexec:$PATH";
  fi
  export LP3D_DIST_DIR=lpub3d_macos_3rdparty;
fi
# Initialize Dropbox storage uploader
[ "$TRAVIS_SECURE_ENV_VARS" == "false" ] || openssl aes-256-cbc -K $encrypted_cacf73a1954d_key -iv $encrypted_cacf73a1954d_iv -in ${LP3D_UPLOADER_DIR}/.dropbox_uploader_travis.enc -out ${LP3D_UPLOADER_DIR}/.dropbox_uploader -d;
