#!/bin/bash
#
# Travis build [before_deploy] procedures
#
#  Trevor SANDY <trevor.sandy@gmail.com>
#  Last Update: December 19, 2017
#  Copyright (c) 2017 by Trevor SANDY
#
cd $LP3D_BUILD_FOLDER

# Gather up and move build artefacts and logs to releases directory
if [ "$LP3D_BUILD_PKG" = "yes" ]; then
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    if [ "$LP3D_BUILD_ARCH170101" = "true" ]; then
      Df_Pkg=`ls $ComposePath/LPub3D-${LP3D_APP_VERSION_LONG}*.pkg.tar.xz`;
      Uf_Pkg=`ls $ComposePath/LPub3D_UpdateMaster_${LP3D_APP_VERSION}*.pkg.tar.xz`;
      cp -f $Df_Pkg $Uf_Pkg *.log $LP3D_RELEASE_DIR;
    fi;
    if [ "$LP3D_BUILD_FEDORA25" = "true" ]; then
      Df_Rpm=`ls $ComposePath/LPub3D-${LP3D_APP_VERSION_LONG}*.rpm`;
      Uf_Rpm=`ls $ComposePath/LPub3D_UpdateMaster_${LP3D_APP_VERSION}*.rpm`;
      cp -f $Df_Rpm $Uf_Rpm *.log $LP3D_RELEASE_DIR;
    fi;
    if [ "$LP3D_BUILD_XENIAL" = "true" ]; then
      Df_Deb=`ls $ComposePath/LPub3D-${LP3D_APP_VERSION_LONG}*.deb`;
      Uf_Deb=`ls $ComposePath/LPub3D_UpdateMaster_${LP3D_APP_VERSION}*.deb`;
      cp -f $Df_Deb $Uf_Deb *.log $LP3D_RELEASE_DIR;
    fi;
  fi;
  if [ "$LP3D_BUILD_MACOS" = "true" ]; then
    Df_Dmg=`ls $DmgBuildPath/DMGS/LPub3D*.dmg`;
    Uf_Dmg=`ls $DmgBuildPath/DMGS/LPub3D-UpdateMaster*.dmg`;
    Logs_Dmg=$(find ../dmgbuild -name *.log)
    cp -f $Df_Dmg $Uf_dmg $Logs_Dmg $LP3D_RELEASE_DIR;
  fi;
  echo " Release Files:" && find $LP3D_RELEASE_DIR -type f;
fi
