#!/bin/bash
#
# Travis build [release] procedures
#
#  Trevor SANDY <trevor.sandy@gmail.com>
#  Last Update: December 21, 2017
#  Copyright (c) 2017 by Trevor SANDY
#
cd $LP3D_BUILD_FOLDER

# Download release files from temperary store
[ -f ${LP3D_UPLOADER_DIR}/.dropbox_uploader ] && './${LP3D_CI_DIR}/dropbox_uploader download $LP3D_RELEASE_DIR/ $LP3D_RELEASE_DIR/'

# List files in the Releases directory
echo "Deploying to GitHub releases ...";
if [ -z "$(ls -A $LP3D_RELEASE_DIR)" ]; then
  echo "$LP3D_RELEASE_DIR is empty. GitHub release aborted.";
  export LP3D_DEPLOY_PKG=no;
else
  echo "Release Files:" && find $LP3D_RELEASE_DIR -type f;
fi

