#!/bin/bash
#
# Travis build [script] procedures
#
#  Trevor SANDY <trevor.sandy@gmail.com>
#  Last Update: December 19, 2017
#  Copyright (c) 2017 by Trevor SANDY
#
cd $LP3D_BUILD_FOLDER

# Build distributions package (using docker-compose for linux builds) or just compile the code
if [ "$LP3D_DEPLOY_PACKAGES" = "" ]; then
  if [ "$LP3D_BUILD_PKG" = "yes" ]; then
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      if [ ! -d "${LP3D_COMPOSE_DIR}/${LP3D_DIST_DIR}" ]; then
        ln -sf "$LP3D_DIST_DIR_PATH" "${LP3D_COMPOSE_DIR}/${LP3D_DIST_DIR}" &&
        if test -d "${LP3D_COMPOSE_DIR}/${LP3D_DIST_DIR}"; then echo "$LP3D_DIST_DIR_PATH linked to ${LP3D_COMPOSE_DIR}/${LP3D_DIST_DIR}"; fi;
      else
        echo "Using cached 3rd Party repository ${LP3D_COMPOSE_DIR}/${LP3D_DIST_DIR}";
      fi;
      if [ "$LP3D_BUILD_ARCH2017" = "true" ]; then
        docker-compose -f $LP3D_COMPOSE_DIR/docker-compose-cibuild-linux.yml run --rm archlinux_2017;
      fi;
      if [ "$LP3D_BUILD_FEDORA25" = "true" ]; then
        docker-compose -f $LP3D_COMPOSE_DIR/docker-compose-cibuild-linux.yml run --rm fedora_25;
      fi;
      if [ "$LP3D_BUILD_XENIAL" = "true" ]; then
        docker-compose -f $LP3D_COMPOSE_DIR/docker-compose-cibuild-linux.yml run --rm ubuntu_xenial;
      fi;
      echo "Package Files " && find $LP3D_COMPOSE_DIR -type f -not -name "*ocker*";
    fi;
    if [ "$LP3D_BUILD_MACOS" = "true" ]; then
      if [ ! -d "${DmgBuildPath}/${LP3D_DIST_DIR}" ]; then
        ln -sf "$LP3D_DIST_DIR_PATH" "${DmgBuildPath}/${LP3D_DIST_DIR}" &&
        if test -d "${DmgBuildPath}/${LP3D_DIST_DIR}"; then echo "$LP3D_DIST_DIR_PATH linked to ${DmgBuildPath}/${LP3D_DIST_DIR}"; fi;
      else
        echo "Using cached 3rd Party repository ${DmgBuildPath}/${LP3D_DIST_DIR}";
      fi;
      chmod +x builds/macx/CreateDmg.sh && ./builds/macx/CreateDmg.sh;
      echo "Package Files:" && find $DmgBuildPath/DMGS -type f;
    fi;
  elif [ "$LP3D_COMPILE_SOURCE" = "true" ]; then
    export LPUB3D="${PWD##*/}"; export WD="$(cd ../ && echo "$PWD")";
    if [ ! -d "${WD}/${LP3D_DIST_DIR}" ]; then
      ln -sf "$LP3D_DIST_DIR_PATH" "${WD}/${LP3D_DIST_DIR}" &&
      if test -d "${WD}/${LP3D_DIST_DIR}"; then echo "$LP3D_DIST_DIR_PATH linked to ${WD}/${LP3D_DIST_DIR}"; fi;
    else
      echo "Using cached 3rd Party repository ${WD}/${LP3D_DIST_DIR}";
    fi;
    chmod +x builds/utilities/CreateRenderers.sh && ./builds/utilities/CreateRenderers.sh;
    echo "Renderer Files:" && find ${LP3D_DIST_DIR_PATH} -type f;
    qmake -v;
    qmake -r;
    make;
  fi;
fi
