#!/bin/bash
#
# This commit-msg hook updates the LPub3D version information when
# [build pkg*] or [deploy pkg*] is detected in the commit message.
#
## Automatically generate git revision info
##
## Setup
## > denotes a new line
## cd to your git repository and type:
## $ cat << pbEOF >.git/hooks/commit-msg
## > #!/bin/sh
## > echo "$1" | grep -E '\[(build|deploy) pkg.*\]' &&   # trigger if [build pkg*] or [deploy pkg*] exist in commit message
## > ./builds/utilities/hooks/commit-msg || true         # location of commit-msg script
## > pbEOF
## $
##
## Ignore Increment:
##   In instances where you do NOT want the version info incremented,
##   add the environment variable doIncrement=no to your git call.
##   eg doIncrement=no git commit -m "Message - 00 [ci skip].
##   This is useful when you change the major version number for example.
##
exec 1>&2
increment_version=${doIncrement:-yes}        # to disable or run from command line, set default to 'no'
if test x"$increment_version" = x"yes"; then
  tag_long=`git describe --tags --long`
  tag_short=`git describe --tags --abbrev=0`
  commit_count=`git rev-list HEAD --count`
  sha_hash_short=`git rev-parse --short HEAD`

  valid_commit="yes"
  if test x"`git diff HEAD --name-only`" = x""; then valid_commit="no"; fi

  tmp1=${tag_long#*-}       # remove prefix ending in "-"
  tmp2=${tag_short//./" "}  # replace . with " "
  version_=${tmp2/v/}       # replace v with ""
  revision=${tmp1%-*}
  read major minor patch <<< ${version_}

  echo "0. Incrementing Git version info..."
  echo "   To disable, use: 'doIncrement=FALSE git commit -m \"Commit Message\"'"
  echo "   Old_revision...........$revision"
  echo "   Old_build (count)......$commit_count"
  if test x"$valid_commit" = x"yes"; then ((revision++)); ((commit_count++)); fi

  working_dir=$PWD/mainApp; OBS=true
  chmod +x builds/utilities/update-config-files.sh
  ./builds/utilities/update-config-files.sh ${working_dir} $major $minor $patch $revision $commit_count $sha_hash_short
  git add builds/utilities/version.info
  git add builds/linux/obs/PKGBUILD
  git add builds/linux/obs/debian/changelog
  git add builds/linux/obs/debian/lpub3d-ci.dsc
  git add builds/linux/obs/lpub3d-ci.spec
  git add mainApp/docs/lpub3d${major}${minor}.1
  git add mainApp/docs/README.txt
  git add mainApp/lpub3d.desktop
fi

