#!/bin/bash
#
# This commit-msg hook updates the LPub3D version information when
# [build pkg*] or [deploy pkg*] is detected in the commit message.
#
#  Trevor SANDY <trevor.sandy@gmail.com>
#  Last Update: October 18, 2025
#  Copyright (C) 2017 - 2025 by Trevor SANDY
#
#  Automatically generate git revision info
#
#  Setup
#  '>' denotes a new line
#  cd to your git repository and type:
#  $ cat << pbEOF >.git/hooks/pre-commit
#  > #!/bin/sh
#  > # Confirm master branch and set location of pre-commit script in your source repository
#  > [ "$(git rev-parse --abbrev-ref HEAD)" = "master" ] && ./builds/utilities/hooks/pre-commit || true
#  > pbEOF
#  $
#
#  Ignore Increment:
#    In instances where you do NOT want the version info incremented,
#    add the environment variable inc_rev=no to your git call.
#    e.g. $ env inc_rev=no git commit -m "Message - 00 [ci skip].
#    This is useful on the first commit after you change the
#    major/minor/patch version number for example.
#
# Environment Vars:
#   - inc_rev:   increment revision [Default=yes]
#   - inc_cnt:   increment commit count [Default=yes]
#   - force:     update obs alldeps configuration files [Default=<unset>]
#   - force_all: update all obs configuration files [Default=<unset>]
#
# Flags:
#   -a: update all obs configration files
#   -f: update obs alldeps configuration files
#   -o: update obs configuration files
#   -r: do not increment revision
#   -c: do not increment commit count
#
#  Manual execution examples:
#   Update ALLDEPS configuration files to latest commit
#   $ ./builds/utilities/hooks/pre-commit -f
#
#   Update ALLDEPS configuration files to latest commit and do not increment revision
#   $ ./builds/utilities/hooks/pre-commit -rf
#
#   Update ALLDEPS configuration files to latest commit and do not increment revision or commit count
#   $ ./builds/utilities/hooks/pre-commit -rfc
#
#   Update ALLDEPS configuration files to last commit and do not increment revision
#   $ env force=yes inc_rev=no ./builds/utilities/hooks/pre-commit
#
#   Update ALLDEPS configuration files to last commit, increment revision and commit count and commit changes
#   $ env force=yes git commit -m "Commit message"
#
#   Update ALLDEPS configuration files to latest commit and do not increment revision or commit count; commit changes
#   $ env force=yes inc_rev=no inc_cnt=no git commit -m "Commit message"
#
#   Update OBS configuration files to latest commit
#   $ ./builds/utilities/hooks/pre-commit -o
#
#   Update OBS configuration files to latest commit and do not increment revision
#   $ ./builds/utilities/hooks/pre-commit -ro
#
#   Update OBS configuration files to latest commit and do not increment revision or commit count
#   $ ./builds/utilities/hooks/pre-commit -roc
#
#   Update OBS configuration files to last commit and do not increment revision
#   $ env force=no inc_rev=no ./builds/utilities/hooks/pre-commit
#
#   Update OBS configuration files to last commit, increment revision and commit count and commit changes
#   $ env force=no git commit -m "Commit message"
#
#   Update OBS configuration files to latest commit and do not increment revision or commit count; commit changes
#   $ env force=no inc_rev=no inc_cnt=no git commit -m "Commit message"
#

FILES_PATTERN='\.dropbox_oauth|\.github_api*|\.sfdeploy_travis*'
FORBIDDEN='secrets'
git diff --cached --name-only | \
    egrep "$FILES_PATTERN" && \
    ehco && echo " -Commit rejected - found $FORBIDDEN. Remove and try again" && echo && exit 1 || true

exec 1>&2

# defaults
update_all_files=${force_all:-}
update_alldeps_files=${force:-}
increment_revision=${inc_rev:-yes}
increment_commitcount=${inc_cnt:-yes}

#check for optional config flags
while getopts ":rcaof" opt; do
  case $opt in
  r)
    increment_revision=no
  ;;
  c)
    increment_commitcount=no
  ;;
  a)
    update_all_files=yes
  ;;
  o)
    update_alldeps_files=no
  ;;
  f)
    update_alldeps_files=yes
  ;;
  \?)
    echo "Invalid option: -$OPTARG" >&2
    exit 1
  ;;
  esac
done

release=0
if test x"$update_alldeps_files" = x"yes" || test x"$update_all_files" = x"yes"; then
  obs_alldeps=true
elif test x"$update_alldeps_files" = x"no" && test x"$update_all_files" = x""; then
  obs_alldeps=false
else
  exit 0
fi
obs_deps_dir=builds/linux/obs
obs_alldeps_dir=builds/linux/obs/alldeps
working_dir=$PWD/mainApp

tag_long=`git describe --tags --match v* --long` >/dev/null 2>&1
tag_short=`git describe --tags --match v* --abbrev=0` >/dev/null 2>&1
commit_count=`git rev-list HEAD --count` >/dev/null 2>&1
sha_hash_short=`git rev-parse --short HEAD` >/dev/null 2>&1
last_commit_sha=`git rev-parse HEAD` >/dev/null 2>&1
last_annotated_tag=`git describe --abbrev=0` >/dev/null 2>&1
last_annotated_tag_sha=`git rev-list -n 1 $last_annotated_tag` >/dev/null 2>&1
lp3d_git_ver_author=`git log -1 $last_commit_sha --pretty="%aN"` >/dev/null 2>&1
lp3d_git_ver_committer_email=`git log -1 $last_commit_sha --pretty="%cE"` >/dev/null 2>&1

tmp1=${tag_long#*-}                                     # remove everything before and including "-"
revision=${tmp1%-*}                                     # remove everything after and including "-"
tmp1=${tag_short//./" "}                                # replace . with " "
version_=${tmp1/v/}                                     # replace v with ""
tmp1=${version_#*_}                                     # remove everything before and including "_" if exist
if test "$tmp1" != "$version_"; then suffix=${tmp1}; fi # check if ver_tmp not same as version_ - suffix exist
if test -n "$suffix"; then version_=${version_%_*}; fi  # remove everything after and including "_" - suffix exist
read major minor patch <<< ${version_}

echo "0. Incrementing Git version info..."
echo "   Old revision............$revision"
echo "   Old commit count........$commit_count"
echo "   Increment revision......$increment_revision"
echo "   Increment commit count..$increment_commitcount"

if test x"$increment_revision" = x"yes"; then ((revision++)); fi
if test x"$increment_commitcount" = x"yes"; then ((commit_count++)); fi
if test x"$last_commit_sha" = x"$last_annotated_tag_sha"; then release=1; fi
if test x"$release" = x"1"; then release_build=yes; else release_build=no; fi

if test x"$lp3d_git_ver_author" = x""; then lp3d_git_ver_author=`echo $USER`; fi
if test x"$lp3d_git_ver_committer_email" = x""; then lp3d_git_ver_committer_email=undefined; fi

echo "   New revision............$revision"
echo "   New commit count........$commit_count"
echo "   Release build...........$release_build"

#                       1.      2.      3.      4.         5.             6.               7.        8.                    9.                            10.      11.
# Arguments: \$working_dir \$major \$minor \$patch \$revision \$commit_count \$sha_hash_short \$release \$lp3d_git_ver_author \$lp3d_git_ver_committer_email \$suffix
chmod +x builds/utilities/update-config-files.sh && \
env OBS=$obs_alldeps ./builds/utilities/update-config-files.sh $working_dir $major $minor $patch $revision $commit_count $sha_hash_short $release "$lp3d_git_ver_author" "$lp3d_git_ver_committer_email" $suffix

git add builds/utilities/version.info
git add mainApp/docs/lpub3d${major}${minor}.1
git add mainApp/docs/README.txt
git add mainApp/docs/RELEASE_NOTES.html
git add mainApp/lpub3d.desktop
git add mainApp/lpub3d.appdata.xml
git add mainApp/extras/LPub3D_Npp_UDL.xml
git add README.md
git add gitversion.pri

git add ${obs_deps_dir}/PKGBUILD
git add ${obs_deps_dir}/lpub3d-ci.spec
git add ${obs_deps_dir}/debian/lpub3d-ci.dsc
git add ${obs_deps_dir}/debian/changelog
git add ${obs_deps_dir}/debian/rules
if test x"$obs_alldeps" = x"true"; then
  git add ${obs_alldeps_dir}/PKGBUILD
  git add ${obs_alldeps_dir}/PKGBUILD-qt5
  git add ${obs_alldeps_dir}/lpub3d-ci.spec
  git add ${obs_alldeps_dir}/lpub3d-ci-qt5.spec
  git add ${obs_alldeps_dir}/debian/lpub3d-ci.dsc
  git add ${obs_alldeps_dir}/debian/lpub3d-ci-qt5.dsc
fi

echo "   Staged files:"
for file in $(git diff --name-only --cached); do
  echo "   -$file"
done
