FROM base/archlinux:2017.10.01
LABEL maintainer "Trevor SANDY <trevor.sandy@gmail.com>"
RUN pacman -Suu
RUN pacman -S git wget curl
RUN pacman -S qt5-base qt5-tools libpng libjpeg-turbo
RUN pacman -S libtiff freeglut mesa boost
VOLUME /buildpkg
CMD wget https://raw.githubusercontent.com/trevorsandy/lpub3d-ci/master/builds/linux/CreateDeb.sh \
    && chmod +x CreateDeb.sh \
    && ./CreateDeb.sh \
    && if test -d /buildpkg; then cp -f /debbuild/*.deb /buildpkg/; fi
